services:
  app:
    image: multivrss-app:latest
    restart: unless-stopped
    env_file: .env.production
    networks:
      - internal
    depends_on:
      - db
      - meilisearch

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file: .env.production
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal

  meilisearch:
    image: getmeili/meilisearch:v1.13
    restart: unless-stopped
    env_file: .env.production
    volumes:
      - meilidata:/meili_data
    networks:
      - internal


networks:
  internal:

volumes:
  pgdata:
  meilidata:
