services:
  app:
    image: ghcr.io/trnqeu/multivrss:${IMAGE_TAG:-latest}
    pull_policy: always
    restart: unless-stopped
    env_file: ${ENV_FILE:-.env.production}
    ports:
    - "127.0.0.1:3001:3000"
    networks:
      - internal
    depends_on:
      - db
      - meilisearch
      - redis

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file: ${ENV_FILE:-.env.production}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal

  meilisearch:
    image: getmeili/meilisearch:v1.13
    restart: unless-stopped
    env_file: ${ENV_FILE:-.env.production}
    volumes:
      - meilidata:/meili_data
    networks:
      - internal

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - redisdata:/data

  worker:
    image: ghcr.io/trnqeu/multivrss:${IMAGE_TAG:-latest}
    pull_policy: always
    restart: unless-stopped
    command: node dist/worker.js
    env_file: ${ENV_FILE:-.env.production}
    networks:
      - internal
    depends_on:
      - redis
      - db

  adminer:
    image: adminer
    restart: "no"
    profiles: ["tools"]
    ports:
      - "127.0.0.1:8082:8080"
    networks:
      - internal


networks:
  internal:

volumes:
  pgdata:
  meilidata:
  redisdata:
